#pragma once

#include "stdafx.h"

#include "atlstr.h"
#include "windows.h"

static LPWSTR strHelpENG[] = { L"ALL ACTIONS",
L"Screen off: Turns off screen immediately. To wake the screen on, just move, click mouse or press any key on keyboard.",
L"Sleep: The PC stays on but uses low power. Apps stay open so when the PC wakes up, you're instantly back to where you left off.",
L"Shutdown: Closes all apps and then turns off the PC.",
L"Restart: Turns off the PC and then turns it on again.",
L"Sign out: Closes all apps and signs you out."
L"Hibernate: Turns off the PC but apps stay open. When the PC is turned on, you're back to where you left off.",
L" ",
L" ",
L"TRAY/NOTIFY ICON",
L"A small icon is shown in the system tray. Move the cursor on it to show the information about the selected action. Click left and right mouse button on it to perform the selected action. Click the mouse wheel on it to show the application's main window.",
L" ",
L" ",
L"BASIC/MAIN SETTINGS",
L"Left Mouse Button: Setup the primary action for application. Action will be performed when you click the left mouse button on the Tray/Notify icon.",
L"Right Mouse Button: Setup the secondary action for application. Action will be performed when you click the right mouse button on the Tray/Notify icon. By default, the setting for this action is \"Just show menu\".",
L"Just show menu (Check Box): Allow you select between \"Just show menu\" and other actions for the \"Right mouse button\" setting. If this is ticked, the application will just show menu when you click right mouse button on Tray/Notify icon.",
L" ",
L" ",
L"ADVANCED OPTIONS",
L"Show this dialog box at startup: Allow you select between show or hide the application's main window. If this is not ticked, the main windows will be hide and just show the icon in system tray when you run the application.",
L"Startup with Windows: Allow you activate or disable the auto-startup function. If this auto-startup function is on and the application will be run automatically as soon as Windows finished starting.",
L"Ask before performing: Activate or disable the action confirming function. If this function is on and the application will show a message box in order to ensure whether you really want to perform the selected action or not.",
L"Save the log of actions: Activate or disable the log saving function. If this function is on, the application will save the log when an action is performed.",
L"Show error message on screen: Activate or disable the error alert function. If this function is on, the application will show an alert about what error happened when performing action.",
L"Remind before doing scheduled action: Activate or disable the schedule notificating function. If this function is on, a notification will be appear if a scheduled action will be performed in 30 seconds later.",
L" ",
L"Language: Allow you select the primary language to display for the application. There are two language package installed: English and Vietnamese. ",
L"View the log of actions: Open the action log file for viewing using Notepad if this file is exist.",
L"Backup settings: Backing up all configuration and settings information from Windows registry to a binary registry file. To restore the backed up configuration, just running this file or opening it by Registry Editor from Windows Explorer.",
L"Action Schedule: Open the schedule setting window to view, edit the scheduled action or create a new scheduled action.",
L" ",
L" ",
L"SCHEDULE SETTINGS",
L"Active schedule action: Active or disable scheduled action. This also allow you create/activate a new scheduling or disable/delete a scheduled action.",
L"Time Setting: Set up the time for the action, include time and date to perform action. The scheduled action will be perform automatically on this time.",
L"Do schedule everyday: If this setting is on, you just need to set the time for action. The action will be performed automatically on this time every day.",
L" " };

static LPWSTR strHelpVIE[] = { L"CÁC HÀNH ĐỘNG",
L"Tắt màn hình : Tắt màn hình ngay lập tức.Để bật màn hình, chỉ cần di chuyển, nhấp chuột hoặc nhấn phím bất kỳ.",
L"Ngủ : Máy tính vẫn chạy nhưng sử dụng nguồn điện thấp.Các ứng dụng luôn mở để khi máy tính khởi động, bạn sẽ ngay lập tức trở lại nơi bạn đã dừng lại.",
L"Tắt máy : Đóng tất cả các ứng dụng và sau đó tắt máy tính.",
L"Khởi động lại : Tắt máy tính và sau đó bật lại.",
L"Đăng xuất : Đóng tất cả ứng dụng và đăng xuất tài khoản của bạn.",
L"Ngủ đông : Tắt máy tính nhưng ứng dụng vẫn mở.Khi máy tính được bật, bạn sẽ trở lại nơi bạn đã dừng lại.",
L" ",
L" ",
L"BIỂU TƯỢNG KHAY HỆ THỐNG",
L"Một biểu tượng nhỏ của ứng dụng này được hiển thị trong khay hệ thống.Di chuyển con trỏ trên nó để hiển thị thông tin về hành động đã chọn.Nhấp chuột trái và nút chuột phải vào nó để thực hiện hành động đã chọn.Nhấn nút cuộn chuột trên nó để hiển thị cửa sổ chính của ứng dụng.",
L" ",
L" ",
L"CÁC THIẾT LẬP CƠ BẢN",
L"Nút chuột trái : Thiết lập hành động chính cho ứng dụng.Hành động sẽ được thực hiện khi bạn nhấp vào nút chuột trái trên biểu tượng hệ thống.",
L"Nút chuột phải : Thiết lập hành động phụ cho ứng dụng.Hành động sẽ được thực hiện khi bạn nhấp vào nút chuột phải trên biểu tượng hệ thống.Theo mặc định, cài đặt cho hành động này là \"Chỉ hiển thị menu\".",
L"Chỉ hiển thị menu : Cho phép bạn chọn giữa \"Chỉ hiển thị menu\" và các hành động khác cho cài đặt \"Nút chuột phải\".Nếu ô này được đánh dấu, ứng dụng sẽ chỉ hiển thị menu khi bạn nhấp chuột phải vào biểu tượng hệ thống.",
L" ",
L" ",
L"CÁC THIẾT LẬP NÂNG CAO",
L"Hiển thị hộp thoại này khi khởi động : Cho phép bạn chọn giữa hiển thị hoặc ẩn cửa sổ chính của ứng dụng.Nếu ô này không được đánh dấu, cửa sổ chính sẽ được ẩn và chỉ hiển thị biểu tượng trong khay hệ thống khi bạn chạy ứng dụng.",
L"Khởi động cùng Windows : Cho phép bạn kích hoạt hoặc vô hiệu hóa chức năng tự khởi động.Nếu chức năng khởi động tự động này được bật và ứng dụng sẽ được chạy tự động khi Windows khởi động.",
L"Hỏi trước khi thực hiện : Kích hoạt hoặc vô hiệu hóa chức năng xác nhận hành động.Nếu chức năng này được bật và ứng dụng sẽ hiển thị một hộp thông báo để xác nhận bạn có thực sự muốn thực hiện hành động đã chọn hay không.",
L"Lưu nhật ký hành động : Kích hoạt hoặc vô hiệu hóa chức năng lưu nhật ký hành động.Nếu chức năng này được bật, ứng dụng sẽ lưu nhật ký khi một hành động được thực hiện.",
L"Hiển thị thông báo lỗi trên màn hình : Kích hoạt hoặc vô hiệu chức năng thông báo lỗi.Nếu chức năng này được bật, ứng dụng sẽ hiển thị thông báo về lỗi đã xảy ra khi thực hiện hành động.",
L"Nhắc nhở trước khi thực hiện lịch : Kích hoạt hoặc vô hiệu hóa chức năng thông báo lịch.Nếu chức năng này được bật, một thông báo sẽ xuất hiện nếu hành động được lên lịch sẽ được thực hiện trong 30 giây sau đó.",
L" ",
L"Ngôn ngữ : Cho phép bạn chọn ngôn ngữ chính để hiển thị cho ứng dụng.Có hai gói ngôn ngữ được cài đặt : Tiếng Anh và Tiếng Việt.",
L"Xem nhật ký hành động : Mở tập tin nhật ký hành động để xem bằng Notepad nếu tập tin này tồn tại.",
L"Sao lưu thiết lập : Sao lưu tất cả thông tin cấu hình và cài đặt từ Windows registry sang tập tin registry.Để khôi phục thiết lập đã sao lưu, chỉ cần chạy tập tin này hoặc mở nó bằng Registry Editor từ Windows Explorer.",
L"Hẹn giờ : Mở cửa sổ cài đặt lịch trình để xem, chỉnh sửa hành động theo lịch biểu hoặc tạo hành động theo lịch mới.",
L" ",
L" ",
L"CÀI ĐẶT LỊCH",
L"Kích hoạt chức năng lịch hoạt động : Hoạt động hoặc vô hiệu hoá hành động theo lịch.Điều này cũng cho phép bạn tạo / kích hoạt một lịch trình mới hoặc vô hiệu hóa / xóa một hành động theo lịch trình.",
L"Thiết lập thời gian : Thiết lập thời gian cho hành động, bao gồm ngày và giờ để thực hiện hành động.Hành động được lên lịch sẽ được thực hiện tự động vào thời điểm này.",
L"Thực hiện lịch biểu hàng ngày : Nếu chức năng này được bật, bạn chỉ cần đặt thời gian để hành động.Hành động sẽ được thực hiện tự động vào thời gian này mỗi ngày.",
L" " };